message = input("Infinitive verb: ")
message = message.strip().lower()

irregular_verbs = {
    "to be": "was/were been",
    "to beat": "beat beaten",
    "to become": "became become",
    "to begin": "began begun",
    "to bend": "bent bent",
    "to bet": "bet bet",
    "to bite": "bit bitten",
    "to bleed": "bled bled",
    "to blow": "blew blown",
    "to break": "broke broken",
    "to bring": "brought brought",
    "to build": "built built",
    "to burn": "burnt burnt",
    "to burst": "burst burst",
    "to buy": "bought bought",
    "to catch": "caught caught",
    "to choose": "chose chosen",
    "to come": "came come",
    "to cost": "cost cost",
    "to creep": "crept crept",
    "to cut": "cut cut",
    "to deal": "dealt dealt",
    "to dig": "dug dug",
    "to do": "did done",
    "to draw": "drew drawn",
    "to dream": "dreamt dreamt",
    "to drink": "drank drunk",
    "to drive": "drove driven",
    "to dwell": "dwelt dwelt",
    "to eat": "ate eaten",
    "to fall": "fell fallen",
    "to feed": "fed fed",
    "to feel": "felt felt",
    "to fight": "fought fought",
    "to find": "found found",
    "to flee": "fled fled",
    "to fly": "flew flown",
    "to forbid": "forbade forbidden",
    "to forget": "forgot forgotten",
    "to forgive": "forgave forgiven",
    "to freeze": "froze frozen",
    "to get": "got gotten",
    "to give": "gave given",
    "to go": "went gone",
    "to grow": "grew grown",
    "to have": "had had",
    "to hear": "heard heard",
    "to hide": "hid hidden",
    "to hit": "hit hit",
    "to hold": "held held",
    "to keep": "kept kept",
    "to know": "knew known",
    "to learn": "learned/learnt learned/learnt",
    "to leave": "left left",
    "to lend": "lent lent",
    "to let": "let let",
    "to lie": "lay lain",
    "to light": "lit lit",
    "to lose": "lost lost",
    "to make": "made made",
    "to mean": "meant meant",
    "to meet": "met met",
    "to pay": "paid paid",
    "to put": "put put",
    "to read": "read read",
    "to ride": "rode ridden",
    "to ring": "rang rung",
    "to rise": "rose risen",
    "to run": "ran run",
    "to say": "said said",
    "to see": "saw seen",
    "to sell": "sold sold",
    "to send": "sent sent",
    "to set": "set set",
    "to shake": "shook shaken",
    "to shine": "shone shone",
    "to shoot": "shot shot",
    "to show": "showed shown",
    "to shut": "shut shut",
    "to sing": "sang sung",
    "to sit": "sat sat",
    "to sleep": "slept slept",
    "to speak": "spoke spoken",
    "to spend": "spent spent",
    "to spin": "spun spun",
    "to stand": "stood stood",
    "to steal": "stole stolen",
    "to stick": "stuck stuck",
    "to sting": "stung stung",
    "to stink": "stank stunk",
    "to strike": "struck struck",
    "to swear": "swore sworn",
    "to sweep": "swept swept",
    "to swim": "swam swum",
    "to take": "took taken",
    "to teach": "taught taught",
    "to tell": "told told",
    "to think": "thought thought",
    "to throw": "threw thrown",
    "to understand": "understood understood",
    "to wake": "woke woken",
    "to wear": "wore worn",
    "to weave": "wove woven",
    "to win": "won won",
    "to write": "wrote written"
}
output = ""
if message.startswith("to "):
    message = message[3:]

verb_forms = irregular_verbs.get(f"to {message}")

if verb_forms:
    output += verb_forms
else:
    output += f"Invalid verb: {message} not found in dictionary. "

print(output)





